name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.java'
      - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn editorconfig:check clean package